#!/bin/bash

# Env Vars:
# REGISTRY: name of the image registry/namespace to get the images

# Clean up previous run
function clean() {
  set +ex
  echo Cleaning...
  (
  ibmcloud ce app delete -n hello -f
  rm -f out
  ) > /dev/null 2>&1
}

clean
[[ "$1" == "clean" ]] && exit 0

set -ex
export REGISTRY=${REGISTRY:-icr.io/codeengine}

# Create the app
ibmcloud ce app create -n wdb --image ${REGISTRY}/wd_bridge

# Get the URL of the app for later use
URL=$(ibmcloud ce app get -n wd_bridge -o url)

# Now call it
curl -fs $URL | tee out
[[ "${PIPESTATUS[0]}" == "0" ]]

if ! [[ "$(cat out)" == "watson discovery bridge!" ]]; then
  echo "Unexpected output"
  exit 1
fi

# Clean up
clean
